name: build
on: [push, pull_request]
jobs:
  #windows: # VERSION ISSUES W/ TEXLIVE, REPLACE W/ TLMGR LIKE ON MACOS
  #  runs-on: windows-latest
  #  defaults:
  #    run:
  #      shell: msys2 {0}
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: msys2/setup-msys2@v2
  #      with:
  #        msystem: MINGW64
  #        update: true
  #        install: make mingw-w64-x86_64-gcc mingw-w64-x86_64-perl-win32-tieregistry
  #    - name: Install Dependencies
  #      run: |
  #        : # Fix Perl locale issue
  #        export LC_ALL=en_US.utf8
  #        : # Fix Perl search path/Win32::TieRegistry version issue
  #        dir=D:/a/_temp/msys64/mingw64/lib/perl5/site_perl
  #        mkdir -p $dir/5.38.2/Win32
  #        ln $dir/5.32.1/Win32/TieRegistry.pm $dir/5.38.2/Win32/TieRegistry.pm
  #        : # Downgrade zlib version to match LuaLaTex
  #        pkg=mingw-w64-x86_64-zlib
  #        ver=1.3-1
  #        file=$pkg-$ver-any.pkg.tar.zst
  #        curl -LO https://repo.msys2.org/mingw/mingw64/$file
  #        pacman -U --noconfirm $file
  #        : # Install TeX Live packages
  #        pacman -S --noconfirm mingw-w64-x86_64-texlive-luatex mingw-w64-x86_64-texlive-latex-extra mingw-w64-x86_64-texlive-fonts-extra
  #    - name: Build and Test
  #        run: make -j
  #    - uses: actions/upload-artifact@v4
  #      with:
  #        name: windows-build
  #        path: libpgfplotter.a
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: melusina-org/setup-macports@v1
      - name: Install Dependencies
        run: |
          curl -LO https://mirror.ctan.org/systems/mac/mactex/BasicTeX.pkg
          sudo installer -pkg BasicTeX.pkg -target /
          export PATH=/Library/TeX/texbin:$PATH
          sudo tlmgr update --self
          sudo tlmgr install standalone xstring luatex85 newtx pgfplots siunitx fontaxes txfonts
          sudo port install ghostscript poppler
      - name: Build and Test
        run: |
          export PATH=/Library/TeX/texbin:$PATH
          make -j
      - uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: libpgfplotter.a
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt install texlive-luatex texlive-latex-extra texlive-fonts-extra texlive-xetex texlive-science ghostscript poppler-utils
      - name: Build and Test
        run: make -j
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: libpgfplotter.a
